.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EUBIND 1 "January 8, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
eubind \- Creates standalone euphoria executables
.SH SYNOPSIS
.B eubind
.RI " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B eubind
command.  eubind is used for creating standalone executables from euphoria 
programs.  The code is parsed and converted to euphoria IL code, and combined
with the compiled backend.  The result is a file that can be run on its own,
without the euphoria interpreter.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBeuphoria\fP is a program that...
.SH SEE ALSO
.BR exu (1),
.BR ecu (1),
.BR eushroud (1)
.BR eubackend (1)
.br
The programs are documented fully
in /usr/share/euphoria/html
.SH AUTHOR
euphoria was written by Robert Craig <rds@rapideuphoria.com>.
.PP
This manual page was written by Matt Lewis <matthewwalkerlewis@gmail.com>,
for the Debian project (but may be used by others).
