#!/bin/bash
# build everything for Linux
echo Translator library
chmod +x gnulib
./gnulib
echo moving translator library to euphoria/bin
mv ecu.a $EUDIR/bin

echo Interpreter
chmod +x imakeu
./imakeu

echo Back-end for binding
chmod +x bmakeu
./bmakeu

echo Translator 
exu ec.ex ec.ex  
./emake
mv ec ecu
ls -l ecu

echo moving programs to euphoria/bin
mv exu $EUDIR/bin
mv backendu $EUDIR/bin
mv ecu $EUDIR/bin



