-- update the CURL constants with:
-- eui curlimport.ex < /usr/include/curl/curl.h > ../include/std/curl.e


include std/regex.e as regex
constant macroconstant     = regex:new("^ *#define +([A-Z][A-Z_]*) +([0-9]+)")
constant curloptionpattern = regex:new("CINIT\\(([A-Z_0-9]+), [A-Z]+, ([0-9]+)")
object line
printf(1, "-- Do not edit this file:  use source/curlimport.ex to generate it.\n", {})
puts(1, "export constant\n")
while sequence(line) with entry do
    object m = regex:matches( curloptionpattern, line)
    if sequence(m) then
     	printf(1, repeat(' ',8) & "CURLOPT_%s = %s,\n", {m[2], m[3]}) 
    end if
    m = regex:matches( macroconstant, line)
    if sequence(m) then
	printf(1, repeat(' ',8) & "%s = %s,\n", {m[2], m[3]})
    end if 
entry
     line = gets(0)
end while
puts(1, "$\n")
