-- (c) Copyright - See License.txt

ifdef ETYPE_CHECK then
	with type_check
elsedef
	without type_check
end ifdef

include std/filesys.e
include std/locale.e
include std/text.e

include common.e


-- This type-enum should be in value order.  That is, a value that appears after the another shall always be greater than the other.  Instead of adding another value to this enum type at the end of the list, change one of the DELETED ids (DELETED_A, DELTED_B) to a new message name.  You'll need to change it also in StdErrMsgs below.  Its message will be "-deleted-".  
-- Please maintain the members of StdErrMsgs in alphabetic name order by moving your changed entry.   Alphabetic name order means the names of the members in the source file appear in alphabetic order.  Notice that UNKNOWN_MESSAGE_CODE_1 appears at the end of StdErrMsgs, even though it has a value of 0 in the type enum.  Notice as well that UNKNOWN_OP_CODE_1 appears near UNKNOWN_MESSAGE_CODE_1 in StdErrMsgs. The corresponding StdErrMsgs member should be "-deleted-" before you change it. 
public type enum message_index
    UNKNOWN_MESSAGE_CODE_1=0,
    MSG_1_IS_MISSING_DEFINED_WORD_BEFORE_OR,
    MSG_1_IS_MISSING_DEFINED_WORD_BEFORE_AND,
    MSG_1_WORD_MUST_BE_AN_IDENTIFIER,
    MSG_1_NOT_UNDERSTOOD,
    MSG_1_IS_NOT_SUPPORTED_IN_EUPHORIA_FOR_2,
    MSG_1_IS_MISSING_DEFINED_WORD_BEFORE_THEN,
    MSG_1_DUPLICATE_NOT,
    MSG_1_THEN_FOLLOWS_2,
    MSG_1_OR_FOLLOWS_2,
    MSG_1_AND_FOLLOWS_2,
    MSG_1_THEN_FOLLOWS_NOT,
    MSG_1_CONFLICTS_WITH_A_FILE_NAME_USED_INTERNALLY_BY_THE_TRANSLATOR,
    MSG_WITH_FALLTHRU_IS_ONLY_VALID_IN_A_SWITCH_STATEMENT,
    MSG_WITH_ENTRY_IS_ONLY_VALID_ON_A_WHILE_OR_LOOP_STATEMENT,
    MSG_WITHOUT_FALLTHRU_IS_ONLY_VALID_IN_A_SWITCH_STATEMENT,
    MSG_PUBLIC_OR_EXPORT_MUST_BE_FOLLOWED_BYA_TYPE_CONSTANT_ENUM_PROCEDURE_TYPE_OR_FUNCTION,
    MSG_END_HAS_NO_MATCHING_1,
    MSG_GLOBAL_MUST_BE_FOLLOWED_BYA_TYPE_CONSTANT_ENUM_PROCEDURE_TYPE_OR_FUNCTION,
    MSG_1_HAS_NOT_BEEN_DECLARED,
    MSG_1_NEEDS_2_ARGUMENT,
    MSG__MUST_ONLY_APPEAR_BETWEEN__AND__OR_AS_THE_LAST_ITEM_IN_A_SEQUENCE_LITERAL,
    A_FALLTHRU_MUST_BE_INSIDE_A_SWITCH,
    A_NAMESPACE_QUALIFIER_IS_NEEDED_TO_RESOLVE_1BECAUSE_2_IS_DECLARED_AS_A_GLOBALPUBLIC_SYMBOL_IN3,
    A_VARIABLE_NAME_IS_EXPECTED_HERE,
    FOUND__1__BUT_WAS_EXPECTING_AN_IDENTIFIER_NAME,
    ARGUMENT_1_OF_2_3_WAS_OMITTED_BUT_THERE_IS_NO_DEFAULT_VALUE_DEFINED,
    AN_UNKNOWN_WITHWITHOUT_OPTION_HAS_BEEN_SPECIFIED,
    A_LOOP_VARIABLE_NAME_IS_EXPECTED_HERE,
    ARGUMENT_1_WAS_OMITTED_BUT_THERE_IS_NO_DEFAULT_VALUE_DEFINED,
    AN_ENUM_CONSTANT_MUST_BE_AN_INTEGER,
    ATTEMPT_TO_REDEFINE_1,
    AN_IDENTIFIER_IS_EXPECTED_HERE,
    A_CASE_BLOCK_CANNOT_FOLLOW_A_CASE_ELSE_BLOCK,
    A_CASE_MUST_BE_INSIDE_A_SWITCH,
    A_LABEL_CLAUSE_MUST_BE_FOLLOWED_BY_A_CONSTANT_STRING,
    A_NEW_NAMESPACE_IDENTIFIER_IS_EXPECTED_HERE,
    A_TYPE_IS_EXPECTED_HERE,
    A_LABEL_CLAUSE_MUST_BE_FOLLOWED_BY_A_LITERAL_STRING,
    BREAK_MUST_BE_INSIDE_AN_IF_BLOCK,
    BREAK_STATEMENT_MUST_BE_INSIDE_A_IF_OR_A_SWITCH_BLOCK,
    BADLYFORMED_LIST_OF_PARAMETERS__EXPECTED__OR,
    BLOCK_COMMENT_FROM_LINE_1_NOT_TERMINATED,
    COMPILER_IS_UNKNOWN,
    CASE_ELSE_CANNOT_BE_FIRST_CASE_IN_SWITCH,
    COULDNT_OPEN_12_FOR_WRITING,
    CANNOT_BUILD_A_DLL_FOR_DOS,
    CANT_OPEN_MAINH_FILE_FOR_OUTPUT,
    CANNOT_USE_THE_FILENAME_1_UNDER_DOSUSE_THE_WINDOWS_VERSION_WITH_PLAT_DOS_INSTEAD,
    CONTINUE_STATEMENT_MUST_BE_INSIDE_A_LOOP,
    CONTINUE_MUST_BE_INSIDE_A_LOOP,
    CANT_OPEN_1,
    CANT_FIND_1_IN_ANY_OF_2,
    CANT_OPEN_INITC_FOR_APPEND,
    CANT_OPEN_MAINC_FOR_OUTPUT,
    CANT_OPEN_INITC_FOR_OUTPUT,
    CHARACTER_CONSTANT_IS_MISSING_A_CLOSING,
    COULDNT_OPEN_C_FILE_FOR_OUTPUT,
    DJGPP_OPTION_ONLY_AVAILABLE_FOR_DOS,
    DUPLICATE_LABEL_NAME,
    DJGPP_ENVIRONMENT_VARIABLE_IS_NOT_SET,
    DEFINED_WORD_MUST_ONLY_HAVE_ALPHANUMERICS_AND_UNDERSCORE,
    DIGIT_1_AT_POSITION_2_IS_OUTSIDE_OF_NUMBER_BASE,
    DUPLICATE_CASE_VALUE_USED,
    DUPLICATE_ENTRY_CLAUSE_IN_A_LOOP_HEADER,
    END_OF_FILE_REACHED_WHILE_SEARCHING_FOR_END_IFDEF_TO_MATCH_IFDEF_ON_LINE_1,
    EXPECTED_THEN_OR__NOT_1,
    END_OF_LINE_REACHED_WITH_NO_CLOSING,
    EXPECTED_1_NOT_2,
    EXPECTED__OR,
    ENUM_CONSTANTS_MUST_BE_ASSIGNED_AN_INTEGER,
    EXPECTED_AN_ATOM_STRING_OR_A_CONSTANT_ASSIGNED_AN_ATOM_OR_A_STRING,
    ENTRY_MUST_BE_INSIDE_A_LOOP,
    ENTRY_STATEMENT_IS_BEING_USED_WITHOUT_A_CORRESPONDING_ENTRY_CLAUSE_IN_THE_LOOP_HEADER,
    ERRORS_RESOLVING_THE_FOLLOWING_REFERENCES1,
    EXPECTING_END_IFDEF_TO_MATCH_IFDEF_ON_LINE_1,
    EXPECTED_TO_SEE_AN_ASSIGNMENT_AFTER_1_SUCH_AS__OR,
    EXPECTING_THEN_ON_ELSIFDEF_LINE,
    EXPECTING_A_WORD_TO_FOLLOW_ELSIFDEF,
    EXPECTED_END_OF_1_BLOCK_NOT_2,
    ENTRY_KEYWORD_IS_NOT_SUPPORTED_INSIDE_AN_IF_OR_SWITCH_BLOCK_HEADER,
    EXPECTING_TO_FIND_A_WORD_TO_DEFINE_BUT_REACHED_END_OF_LINE_FIRST,
    EXPECTING_POSSIBLY_THEN_NOT_END_OF_LINE,
    ENTRY_IS_NOT_SUPPORTED_IN_FOR_LOOPS,
    ENUM_CONSTANTS_MUST_BE_INTEGERS,
    EXPECTED_TO_SEE_A_PARAMETER_DECLARATION_NOT,
    EXPONENT_NOT_FORMED_CORRECTLY,
    EXITBREAK_ARGUMENT_OUT_OF_RANGE,
    EXIT_STATEMENT_MUST_BE_INSIDE_A_LOOP,
    EXIT_MUST_BE_INSIDE_A_LOOP,
    FOUND_1_2_BUT_WAS_EXPECTING_A_PARAMETER_NAME_INSTEAD,
    FOUND_1_BUT_EXPECTED_ELSE_AN_ATOM_STRING_CONSTANT_OR_ENUM,
    FOUND_1_BUT_WAS_EXPECTING_A_PARAMETER_NAME_INSTEAD,
    MSG_DELETED,
    FRACTIONAL_PART_OF_NUMBER_IS_MISSING,
    FILE_NAME_IS_MISSING,
    GOTO_STATEMENT_WITHOUT_A_STRING_LABEL,
    HEX_NUMBER_NOT_FORMED_CORRECTLY,
    INTERNAL_NESTED_CALL_PARSING_ERROR,
    INTEGER_OR_CONSTANT_EXPECTED,
    EXPECTING_AS_OR_ENDOF_LINE_UNEXPECTED_TEXT_ON_INCLUDE_DIRECTIVE,
    ILLEGAL_CHARACTER_IN_SOURCE,
    ILLEGAL_CHARACTER,
    ILLEGAL_CHARACTER_ASCII_0_AT_LINECOL_12,
    INCLUDES_ARE_NESTED_TOO_DEEPLY,
    INVALID_NUMBER_BASE_SPECIFIER_1,
    INTERNAL_DEREF_PROBLEM,
    LEAVING_TOO_MANY_BLOCKS_1__2,
    MISMATCHED_ELSE_SHOULD_THIS_BE_AN_ELSEDEF_TO_MATCH_IFDEF_ON_LINE_1,
    MAY_NOT_ASSIGN_TO_A_FORLOOP_VARIABLE,
    MAY_NOT_CHANGE_THE_VALUE_OF_A_CONSTANT,
    MISMATCHED_END_IF_SHOULD_THIS_BE_AN_END_IFDEF_TO_MATCH_IFDEF_ON_LINE_1,
    MULTITASKING_OPERATIONS_ARE_NOT_SUPPORTED_IN_A_DLL_OR_SO,
    MISSING_NAMESPACE_QUALIFIER,
    MISSING_DEFAULT_NAMESPACE_QUALIFIER,
    MISSING_CLOSING_QUOTE_ON_FILE_NAME,
    NOT_EXPECTING_ANYTHING_ON_SAME_LINE_AS_ELSDEF,
    NOT_EXPECTING_TO_SEE_1_HERE,
    NOT_EXPECTING_ELSE,
    NOT_EXPECTING_ELSIF,
    NO_VALUE_RETURNED_FROM_FUNCTION,
    NUMBER_NOT_FORMED_CORRECTLY,
    NO_WORD_WAS_FOUND_FOLLOWING_1,
    OUT_OF_MEMORY__TURN_OFF_TRACE_AND_PROFILE,
    ONLY_ONE_DECIMAL_POINT_ALLOWED,
    ONLY_INTEGER_LITERALS_CAN_USE_THE_01_FORMAT,
    PROGRAM_INCLUDES_TOO_MANY_FILES,
    PUNCTUATION_MISSING_IN_BETWEEN_NUMBER_AND_1,
    RETRY_MUST_BE_INSIDE_A_LOOP,
    RAW_STRING_LITERAL_FROM_LINE_1_NOT_TERMINATED,
    RETURN_MUST_BE_INSIDE_A_PROCEDURE_OR_FUNCTION,
    RETRY_STATEMENT_MUST_BE_INSIDE_A_LOOP,
    SYNTAX_ERROR__EXPECTED_TO_SEE_POSSIBLY_1_NOT_2,
    SYNTAX_ERROR__UNKNOWN_NAMESPACE_1_USED,
    SHOULD_THIS_BE_ELSEDEF_FOR_THE_IFDEF_ON_LINE_1,
    SYNTAX_ERROR__EXPECTED_TO_SEE_AN_EXPRESSION_NOT_1,
    SAMPLE_SIZE_MUST_BE_A_POSITIVE_INTEGER,
    SINGLEQUOTE_CHARACTER_IS_EMPTY,
    SYNTAX_ERROR__EXPECTED_TO_SEE_1_AFTER_2_NOT_3,
    SHOULD_THIS_BE_ELSIFDEF_FOR_THE_IFDEF_ON_LINE_1,
    SORRY_TOO_MANY_C_FILES_WITH_THE_SAME_BASE_NAME,
    THE_ENTRY_STATEMENT_MUST_APPEAR_AT_MOST_ONCE_INSIDE_A_LOOP,
    THE_ENTRY_STATEMENT_CAN_NOT_BE_USED_IN_A_FOR_BLOCK,
    THE_INNERMOST_BLOCK_CONTAINING_AN_ENTRY_STATEMENT_MUST_BE_THE_LOOP_IT_DEFINES_AN_ENTRY_IN,
    THE_ENTRY_STATEMENT_MUST_APPEAR_INSIDE_A_LOOP,
    MSG_TAB_CHARACTER_FOUND_IN_STRING__USE_T_INSTEAD,
    TYPE_CHECK_ERROR_WHEN_INLINING_LITERAL,
    TOO_MANY_WARNING_ERRORS,
    TYPES_MUST_HAVE_EXACTLY_ONE_PARAMETER,
    TYPE_MUST_RETURN_TRUE__FALSE_VALUE,
    UNKNOWN_COMPILER,
    UNKNOWN_BUILD_FILE_TYPE,
    UNKNOWN_BLOCK_LABEL,
    UNKNOWN_NAMESPACE_1_IN_DEFAULT_ARGUMENT,
    UNKNOWN_WITHWITHOUT_OPTION_1,
    UNKNOWN_ESCAPE_CHARACTER,
    UNKNOWN_LABEL_1,
    VARIABLE_1_HAS_NOT_BEEN_DECLARED,
    WRONG_NUMBER_OF_ARGUMENTS_SUPPLIED_FOR_FORWARD_REFERENCET1_2_3_4__EXPECTED_5_BUT_FOUND_6,
    WATCOM_ENVIRONMENT_VARIABLE_IS_NOT_SET,
    WARNING_NAMES_MUST_BE_ENCLOSED_IN,
    MSG__MAY_ONLY_BE_ON_THE_FIRST_LINE_OF_A_PROGRAM,
    MSG_DELETED_A,
    COMPILING_130_2,
    COULDNT_COMPILE_FILE_1,
    STATUS_1_COMMAND_2,
    LINKING_100_1,
    UNKNOWN_COMPILER_TYPE_1,
    UNABLE_TO_LINK_1,
    STATUS_1_COMMAND_2_A,
    MSG_1C_FILES_WERE_CREATED,
    LINK_RESOURCE_FILE_INTO_RESULTING_EXECUTABLE,
    TO_BUILD_YOUR_PROJECT_TYPE_12MAK,
    TO_BUILD_YOUR_PROJECT_INCLUDE_1MAK_INTO_A_LARGER_MAKEFILE_PROJECT,
    TO_BUILD_YOUR_PROJECT_CHANGE_DIRECTORY_TO_1_AND_TYPE_23MAK,
    TO_RUN_YOUR_PROJECT_TYPE_1,
    COMPILING_WITH_1,
    DO_NOT_DISPLAY_STATUS_MESSAGES,
    SET_THE_COMPILER_TO_WATCOM,
    SET_THE_COMPILER_TO_DJGPP,
    SET_THE_COMPILER_TO_GCC,
    SET_THE_COMPILER_DIRECTORY,
    CREATE_A_CONSOLE_APPLICATION,
    CREATE_A_SHARED_LIBRARY,
    CREATE_A_SHARED_LIBRARY_A,
    SET_THE_PLATFORM_FOR_THE_TRANSLATED_CODE,
    USE_A_NONSTANDARD_LIBRARY,
    UNABLE_TO_LINK_RESOURCE_FILE_1_INTO_EXECUTABLE_2,
    SET_THE_STACK_SIZE_WATCOM,
    ENABLE_DEBUG_MODE_FOR_GENERATED_CODE,
    SET_THE_NUMBER_OF_C_STATEMENTS_PER_GENERATED_FILE_BEFORE_SPLITTING,
    KEEP_THE_GENERATED_FILES,
    GENERATE_A_PARTIAL_PROJECT_MAKEFILE,
    GENERATE_A_FULL_MAKEFILE,
    COULD_NOT_REMOVE_DIRECTORY_1,
    MSG_DELETED_B,
    DO_NOT_BUILD_THE_PROJECT_NOR_WRITE_A_BUILD_FILE,
    GENERATECOMPILE_ALL_FILES_IN_DIR,
    SET_THE_OUTPUT_FILENAME,
    EUCEXE_OPTIONS_FILEEX_COMMON_OPTIONS,
    MSG__TRANSLATOR_OPTIONS,
    UNKNOWN_PLATFORM_1__SUPPORTED_PLATFORMS_ARE_2,
    INVALID_MAXIMUM_FILE_SIZE,
    ERROR_MUST_SPECIFY_THE_FILE_TO_BE_TRANSLATED_ON_THE_COMMAND_LINE,
    WARNING_1T2,
    UNABLE_TO_CREATE_WARNING_FILE_1,
    PRESS_ENTER_TO_CONTINUE_Q_TO_QUIT,
    DEFINED_WORDS,
    PRESS_ENTER,
    CANT_CREATE_ERROR_MESSAGE_FILE_1,
    MSG_ENDOFFILE,
    INTERNAL_ERRORT1,
    INTERNAL_ERROR_AT_12T3,
    FAILED_DUE_TO_INTERNAL_ERROR,
    WATCOM_CANNOT_BUILD_TRANSLATED_FILES_WHEN_THERE_IS_A_SPACE_IN_ITS_PARENT_FOLDERS,
    WATCOM_NEEDS_TO_HAVE_AN_INCLUDE_VARIABLE_SET_TO_ITS_INCLUDED_DIRECTORIES,
    WATCOM_SHOULD_HAVE_THE_H_AND_THE_HNT_INCLUDES_AT_THE_FRONT_OF_THE_INCLUDE_VARIABLE__WATCOM_IS_LOCATED_IN_1__THE_INCLUDE_ENVIRONMENT_VARIABLE_IS_2,
    STATEMENTS_HAVE_BEEN_INSERTED_TO_TRACE_EXECUTION_OF_YOUR_PROGRAM,
    MSG_12__STATEMENT_AFTER_3_WILL_NEVER_BE_EXECUTED,
    MSG_12__CALL_TO_3_MIGHT_BE_SHORTCIRCUITED,
    MSG_12__EMPTY_CASE_BLOCK_WITHOUT_FALLTHRU,
    MSG_12__NO_CASE_ELSE_SUPPLIED,
    MSG_12__BUILTIN_ROUTINE_3_OVERRIDDEN,
    MSG_12__BUILTIN_ROUTINE_3_OVERRIDDEN_AGAIN,
    CANT_MIX_PROFILE_AND_PROFILE_TIME,
    MSG_12__UNKNOWN_WARNING_NAME_3,
    MSG_1__MODULE_VARIABLE_2_IS_NEVER_ASSIGNED_A_VALUE,
    MSG_1__PRIVATE_VARIABLE_2_OF_3_IS_NEVER_ASSIGNED_A_VALUE,
    MSG_1__MODULE_CONSTANT_2_IS_NOT_USED,
    MSG_1__MODULE_VARIABLE_2_IS_NOT_USED,
    MSG_1__PARAMETER_2_OF_3_IS_NOT_USED,
    MSG_1__PRIVATE_VARIABLE_2_OF_3_IS_NOT_USED,
    FILE_1_USES_PUBLIC_SYMBOLS_FROM_2_BUT_DOES_NOT_INCLUDE_THAT_FILE,
    MSG_12__IDENTIFIER_3_IN_4_IS_NOT_INCLUDED,
    THE_BUILTIN_1_IN_2_OVERRIDES_THE_GLOBALPUBLIC_1_IN3,
    MSG_1_NEEDS_AT_LEAST_2_PARAMETERS_BUT_SOME_NONDEFAULTABLE_ARGUMENTS_ARE_MISSING,
    MSG_1_NEEDS_2_ARGUMENTS,
    MSG_1_ONLY_NEEDS_2_ARGUMENT,
    MSG_1_ONLY_NEEDS_2_ARGUMENTS,
    TRANSLATING_CODE_PASS,
    MSG__GENERATING,
    MSG_1,
    MSG_DELETED_C,
    COULDNT_OPEN_DELETEDTXT,
    DELETED_SYMBOLS,
    THE_LIST_OF_DELETED_SYMBOLS_IS_IN_DELETEDTXT,
    YOU_MAY_NOW_USE_1_TO_RUN_2,
    YOU_MAY_NOW_RUN_1,
    DELETED_1_UNUSED_ROUTINES_AND_2_UNUSED_VARIABLES,
    ERROR_MUST_SPECIFY_THE_FILE_TO_BE_INTERPRETED_ON_THE_COMMAND_LINE,
    BAD_BB_TEMP_TYPE,
    BAD_BB_ELEM_TYPE,
    BAD_BB_ELEM,
    BAD_SEQ_ELEM,
    THIS_OPCODE_1_SHOULD_NEVER_BE_EMITTED__SUBPROG_2,
    NO_ROUTINE_ID_FOR_1,
    BAD_BB_VAR_TYPE,
    BAD_GTYPE,
    OR_TYPE_T1_IS_1_T2_IS_2,
    UNKNOWN_OPCODE_1,
    ATTEMPTED_TO_REMOVE_INVALID_FORWARD_REFERENCE,
    ERROR_RESOLVING_FORWARD_REFERENCE_IN_CASE_FOR_1,
    BAD_OPERATION__EXPECTED_TYPE_CHECK_1_OR_TYPE_CHECK_FORWARD_2__NOT_3,
    UNRECOGNIZED_FORWARD_REFERENCE_TYPE_1_2,
    NEGATIVE_REF_COUNT_FOR_1,
    UNHANDLED_INLINE_TYPE_1,
    ERROR_WITH_TOKEN_PLAYBACK,
    SET_PRIVATE_SCOPE__UNHANDLED_SCOPE_1,
    SCANNER_UNHANDLED_CLASS_1,
    UNKNOWN_OP_FOUND_WHEN_SHIFTING_CODE_1,
    EUPHORIA_INTERPRETER,
    EUPHORIA_TO_C_TRANSLATOR,
    EUPHORIA_BINDER,
    USING_MANAGED_MEMORY,
    USING_SYSTEM_MEMORY,
    EUCONSOLE,
    SPECIFY_ADDITIONAL_COMPILER_FLAGS_TO_TRANSLATOR,
    PAUSED_PRESS_ANY_KEY,
    MSG_PRESS_ANY_KEY_AND_WINDOW_WILL_CLOSE,
    TURN_ON_BATCH_PROCESSING_DO_NOT_PRESS_ENTER_ON_ERROR,
    SPECIFY_A_CONFIGURATION_FILE,
    DISPLAY_ALL_COPYRIGHT_NOTICES,
    DEFINE_A_PREPROCESSOR_WORD,
    ADD_A_DIRECTORY_TO_BE_SEARCHED_FOR_INCLUDE_FILES,
    DEFINES_A_LOCALIZATION_QUALIFIER,
    DEFINES_THE_BASE_NAME_FOR_LOCALIZATION_DATABASES,
    SETUP_A_PREPROCESSOR,
    FORCE_PREPROCESSING_REGARDLESS_OF_CACHE_STATE,
    ENABLE_ALL_WARNINGS,
    TEST_SYNTAX_ONLY_DO_NOT_EXECUTE,
    DISPLAY_THE_VERSION_NUMBER,
    DEFINES_WARNING_LEVEL,
    WRITE_ALL_WARNINGS_TO_THE_GIVEN_FILE_INSTEAD_OF_STDOUT,
    DEFINES_WARNING_LEVEL_BY_EXCLUSION,
    MSG_1_IS_NOT_SUPPORTED_IN_THIS_PLATFORM,
    IL_CODE_IS_NOT_IN_PROPER_FORMAT,
    NOT_AN_IL_FILE,
    OBSOLETE_IL_FILE_PLEASE_RECREATE_IT_USING_EUPHORIA_40_OR_LATER,
    INTERNAL_ERROR_SEEK_TO_IL_START_FAILED,
    CANT_OPEN_EXECUTABLE_FILE_1,
    INTERNAL_ERROR_BOUND_FILE_MAY_HAVE_BEEN_CORRUPTED,
    COULDNT_OPEN_1,
    NO_EUPHORIA_IL_CODE_TO_EXECUTE,
    DOES_NOT_CREATE_AN_EXECUTABLE_JUST_A_IL_FILE_FOR_EUB_TO_RUN,
    DOES_NOT_DISPLAY_BINDING_INFORMATION,
    LIST_UNUSED_DELETED_SYMBOLS_IN_DELETEDTXT,
    PREPARES_A_FILE_FOR_USE_ON_WINDOWS,
    USER_SUPPLIED_ICON_FILE_USED_IGNORED_WHEN_SHROUDING,
    WINDOWS_ONLY_USES_THE_CURRENT_CONSOLE_RATHER_THAN_CREATING_A_NEW_CONSOLE_IGNORED_WHEN_SHROUDING,
    INCLUDES_SYMBOL_NAMES_IN_IL_DATA,
    THE_NAME_OF_THE_EXECUTABLE_TO_CREATE_THE_DEFAULT_IS_THE_SAME_BASENAME_OF_THE_INPUT_FILE,
    AN_INCLUDE_DIRECTORY_TO_USE,
    DISPLAY_COPYRIGHT_INFORMATION,
    NO_FILE_TO_BIND_WAS_SUPPLIED,
    INVALID_OPTION_1,
    INTERNAL_ERROR_BINDING_SEEK_TO_START_OF_IL_FAILED,
    INTERNAL_ERROR_BINDING_SEEK_TO_CHECKSUM_AREA_FAILED,
    SPECIFY_ADDITIONAL_LINKER_FLAGS_FOR_TRANSLATOR,
    YOUR_CUSTOM_ICON_FILE_IS_TOO_LARGE,
    VERBOSE_OUTPUT,
    MSG_1__MODULE_VARIABLE_2_IS_ASSIGNED_BUT_NEVER_USED,
    MSG_1__PARAMETER_2_OF_3_IS_ASSIGNED_BUT_NEVER_USED,
    MSG_1__PRIVATE_VARIABLE_2_OF_3_IS_ASSIGNED_BUT_NEVER_USED,
    FLAGS_TO_PASS_TO_COMPILER_OVERRIDES_INTERNAL_COMPILER_FLAGS,
    FLAGS_TO_PASS_TO_LINKER_OVERRIDES_INTERNAL_LINKER_FLAGS,
    SKIPPING__130_2_UPTODATE,
    FORCE_BUILDING_EVEN_IF_FILE_IS_UPTODATE,
    MSG_1_IS_DEPRECATED,
    OVERRIDES_THE_VALUE_OF_EUDIR,
    INVALID_CHARACTER_IN_HEX_STRING,
    ONLY_ENUMS_MAY_BE_DECLARED_AS_TYPES,
    FORWARD_REFERENCES_ARE_NOT_SUPPORTED_FOR_ENUMS,
    INDICATE_FILES_OR_DIRECTORIES_FOR_WHICH_TO_GATHER_COVERAGE_STATISTICS,
    SPECIFY_THE_FILENAME_FOR_THE_COVERAGE_DATABASE,
    ERASE_AN_EXISTING_COVERAGE_DATABASE_AND_START_A_NEW_COVERAGE_ANALYSIS,
    COULD_NOT_ERASE_COVERAGE_DATABASE_1,
    COULD_NOT_CREATE_COVERAGE_TABLE_1,
    COULD_NOT_CREATE_COVERAGE_DATABASE_1,
    EXCLUDE_FROM_COVERAGE,
    ERROR_CREATING_REGEX_FOR_COVERAGE_EXCLUSION_PATTERN_1,
    EXPECTING_EXACTLY_TWO_HEXADECIMAL_DIGITS_TO_FOLLOW_THE_X,
    EXPECTING_EXACTLY_FOUR_HEXADECIMAL_DIGITS_TO_FOLLOW_THE_U,
    EXPECTING_EXACTLY_EIGHT_HEXADECIMAL_DIGITS_TO_FOLLOW_THE_U,
    EXPECTING_ONLY_0_1_OR_SPACE_TO_FOLLOW_THE_B,
    A_NUMERIC_LITERAL_WAS_EXPECTED,
    PATH_TO_BACKEND_RUNNER_TO_USE_FOR_BINDING_IGNORED_WHEN_SHROUDING,
    TYPE_CHECK_ERROR__ASSIGNING_A_SEQUENCE_TO_AN_ATOM,
    DELETING_1,
    USER_SUPPLIED_LIBRARY_DOES_NOT_EXIST__1,
    RESOURCE_FILE_DOES_NOT_EXIST__1,
    UNABLE_TO_COMPILE_RESOURCE_FILE_1,
    ERROR_IN_PARSING_SCIENTIFIC_NOTATION,
    THERE_IS_NO_WATCOM_INSTALATION_UNDER_SPECIFIED_WATOM_PATH_1,
    MISSING_CMD_PARAMETER,
    EXTERNAL_DEBUGGER,
    USE_THE_MNOCYGWIN_FLAG_WITH_MINGW,
    SPECIFY_THE_TARGET_ARCHITECTURE_X86_X86_64_ARM,
    UNKNOWN_ARCHITECTURE_1__SUPPORTED_ARCHITECTURES_ARE_2,
    MSG_CC_PREFIX=600,
    NONSTANDARD_LIBRARY,
    DUPLICATE_MULTI_ASSIGN,
    TRACE_LINES_CMD,
    BAD_TRACE_LINES,
    BUILDDIR_IS_FILE,
    BUILDDIR_IS_UNDEFINED,
	NUMBER_IS_TOO_SMALL,
	NUMBER_IS_TOO_BIG,
    $
end type


constant StdErrMsgs = {

    { ADD_A_DIRECTORY_TO_BE_SEARCHED_FOR_INCLUDE_FILES, "Add a directory to be searched for include files" },
    { AN_ENUM_CONSTANT_MUST_BE_AN_INTEGER          , "An enum constant must be an integer" },
    { AN_IDENTIFIER_IS_EXPECTED_HERE               , "an identifier is expected here" },
    { AN_INCLUDE_DIRECTORY_TO_USE                  , "An 'include' directory to use." },
    { AN_UNKNOWN_WITHWITHOUT_OPTION_HAS_BEEN_SPECIFIED, "An unknown 'with/without' option has been specified" },
    { ARGUMENT_1_OF_2_3_WAS_OMITTED_BUT_THERE_IS_NO_DEFAULT_VALUE_DEFINED, "Argument [1] of [2] ([3]) was omitted, but there is no default value defined" },
    { ARGUMENT_1_WAS_OMITTED_BUT_THERE_IS_NO_DEFAULT_VALUE_DEFINED, "Argument [1] was omitted but there is no default value defined" },
    { ATTEMPTED_TO_REMOVE_INVALID_FORWARD_REFERENCE, "Attempted to remove invalid forward reference" },
    { ATTEMPT_TO_REDEFINE_1                        , "attempt to redefine [1]." },
    { A_CASE_BLOCK_CANNOT_FOLLOW_A_CASE_ELSE_BLOCK , "a case block cannot follow a case else block" },
    { A_CASE_MUST_BE_INSIDE_A_SWITCH               , "a case must be inside a switch" },
    { A_FALLTHRU_MUST_BE_INSIDE_A_SWITCH           , "a fallthru must be inside a switch" },
    { A_LABEL_CLAUSE_MUST_BE_FOLLOWED_BY_A_CONSTANT_STRING, "A label clause must be followed by a constant string" },
    { A_LABEL_CLAUSE_MUST_BE_FOLLOWED_BY_A_LITERAL_STRING, "A label clause must be followed by a literal string" },
    { A_LOOP_VARIABLE_NAME_IS_EXPECTED_HERE        , "a loop variable name is expected here" },
    { A_NAMESPACE_QUALIFIER_IS_NEEDED_TO_RESOLVE_1BECAUSE_2_IS_DECLARED_AS_A_GLOBALPUBLIC_SYMBOL_IN3, "A namespace qualifier is needed to resolve '[1]'\nbecause '[2]' is declared as a global/public symbol in:\n[3]" },
    { A_NEW_NAMESPACE_IDENTIFIER_IS_EXPECTED_HERE  , "a new namespace identifier is expected here" },
    { A_NUMERIC_LITERAL_WAS_EXPECTED               , "A numeric literal was expected" },
    { A_TYPE_IS_EXPECTED_HERE                      , "a type is expected here" },
    { A_VARIABLE_NAME_IS_EXPECTED_HERE             , "a variable name is expected here" },
    { BADLYFORMED_LIST_OF_PARAMETERS__EXPECTED__OR , "badly-formed list of parameters - expected ',' or ')'" },
    { BAD_BB_ELEM                                  , "Bad BB_elem" },
    { BAD_BB_ELEM_TYPE                             , "Bad BB_elem type" },
    { BAD_BB_TEMP_TYPE                             , "Bad BB_temp_type" },
    { BAD_BB_VAR_TYPE                              , "Bad BB_var_type" },
    { BAD_GTYPE                                    , "Bad GType" },
    { BAD_OPERATION__EXPECTED_TYPE_CHECK_1_OR_TYPE_CHECK_FORWARD_2__NOT_3, "Bad operation.  Expected TYPE_CHECK ([1]) or TYPE_CHECK_FORWARD ([2]) , not [3]" },
    { BAD_SEQ_ELEM                                 , "Bad seq_elem" },
    { BAD_TRACE_LINES                              , "the -trace-lines option requires a valid number\n" },
    { BLOCK_COMMENT_FROM_LINE_1_NOT_TERMINATED     , "Block comment from line [1] not terminated." },
    { BREAK_MUST_BE_INSIDE_AN_IF_BLOCK             , "break must be inside an if block " },
    { BREAK_STATEMENT_MUST_BE_INSIDE_A_IF_OR_A_SWITCH_BLOCK, "break statement must be inside a if or a switch block" },
    { BUILDDIR_IS_FILE                             , "Error: Specified build directory is a file" },
    { BUILDDIR_IS_UNDEFINED                        , "Error: Specified build directory is undefined (wildcards are not allowed)" },
    { CANNOT_BUILD_A_DLL_FOR_DOS                   , "cannot build a dll for DOS" },
    { CANNOT_USE_THE_FILENAME_1_UNDER_DOSUSE_THE_WINDOWS_VERSION_WITH_PLAT_DOS_INSTEAD, "Cannot use the filename, [1], under DOS.\nUse the Windows version with -plat DOS instead.\n" },
    { CANT_CREATE_ERROR_MESSAGE_FILE_1             , "Can't create error message file: [1]\n" },
    { CANT_FIND_1_IN_ANY_OF_2                      , "can't find '[1]' in any of ...\n[2]" },
    { CANT_MIX_PROFILE_AND_PROFILE_TIME            , "can't mix profile and profile_time" },
    { CANT_OPEN_1                                  , "Can't open '[1]'" },
    { CANT_OPEN_EXECUTABLE_FILE_1                  , "Can't open executable file '[1]'" },
    { CANT_OPEN_INITC_FOR_APPEND                   , "Can't open init-.c for append\n" },
    { CANT_OPEN_INITC_FOR_OUTPUT                   , "Can't open init-.c for output\n" },
    { CANT_OPEN_MAINC_FOR_OUTPUT                   , "Can't open main-.c for output\n" },
    { CANT_OPEN_MAINH_FILE_FOR_OUTPUT              , "Can't open main-.h file for output\n" },
    { CASE_ELSE_CANNOT_BE_FIRST_CASE_IN_SWITCH     , "case else cannot be first case in switch" },
    { CHARACTER_CONSTANT_IS_MISSING_A_CLOSING      , "character constant is missing a closing '" },
    { COMPILER_IS_UNKNOWN                          , "Compiler is unknown" },
    { COMPILING_130_2                              , "Compiling [1:3.0]% [2]" },
    { COMPILING_WITH_1                             , "Compiling with [1]" },
    { CONTINUE_MUST_BE_INSIDE_A_LOOP               , "continue must be inside a loop" },
    { CONTINUE_STATEMENT_MUST_BE_INSIDE_A_LOOP     , "continue statement must be inside a loop" },
    { COULDNT_COMPILE_FILE_1                       , "Couldn't compile file '[1]'" },
    { COULDNT_OPEN_1                               , "Couldn't open '[1]'!" },
    { COULDNT_OPEN_12_FOR_WRITING                  , "Couldn't open [1][2] for writing" },
    { COULDNT_OPEN_C_FILE_FOR_OUTPUT               , "Couldn't open .c file for output" },
    { COULDNT_OPEN_DELETEDTXT                      , "Couldn't open deleted.txt" },
    { COULD_NOT_CREATE_COVERAGE_DATABASE_1         , "Could not create coverage database: [1]" },
    { COULD_NOT_CREATE_COVERAGE_TABLE_1            , "Could not create coverage table: [1]" },
    { COULD_NOT_ERASE_COVERAGE_DATABASE_1          , "Could not erase coverage database: [1]" },
    { COULD_NOT_REMOVE_DIRECTORY_1                 , "Could not remove directory [1]" },
    { CREATE_A_CONSOLE_APPLICATION                 , "Create a console application" },
    { CREATE_A_SHARED_LIBRARY                      , "Create a shared library" },
    { CREATE_A_SHARED_LIBRARY_A                    , "Create a shared library" },
    { DEFINED_WORDS                                , "Defined Words" },
    { DEFINED_WORD_MUST_ONLY_HAVE_ALPHANUMERICS_AND_UNDERSCORE, "defined word must only have alphanumerics and underscore" },
    { DEFINES_A_LOCALIZATION_QUALIFIER             , "Defines a localization qualifier" },
    { DEFINES_THE_BASE_NAME_FOR_LOCALIZATION_DATABASES, "Defines the base name for localization databases" },
    { DEFINES_WARNING_LEVEL                        , "Defines warning level" },
    { DEFINES_WARNING_LEVEL_BY_EXCLUSION           , "Defines warning level by exclusion" },
    { DEFINE_A_PREPROCESSOR_WORD                   , "Define a preprocessor word" },
    { DELETED_1_UNUSED_ROUTINES_AND_2_UNUSED_VARIABLES, "deleted [1] unused routines and [2] unused variables." },
    { DELETED_SYMBOLS                              , "Deleted Symbols\n---------------\n\n" },
    { DELETING_1                                   , "deleting [1]..." },
    { DIGIT_1_AT_POSITION_2_IS_OUTSIDE_OF_NUMBER_BASE, "digit '[1]' at position [2] is outside of number base" },
    { DISPLAY_ALL_COPYRIGHT_NOTICES                , "Display all copyright notices" },
    { DISPLAY_COPYRIGHT_INFORMATION                , "Display copyright information" },
    { DISPLAY_THE_VERSION_NUMBER                   , "Display the version number" },
    { DJGPP_ENVIRONMENT_VARIABLE_IS_NOT_SET        , "DJGPP environment variable is not set" },
    { DJGPP_OPTION_ONLY_AVAILABLE_FOR_DOS          , "DJGPP option only available for DOS." },
    { DOES_NOT_CREATE_AN_EXECUTABLE_JUST_A_IL_FILE_FOR_EUB_TO_RUN, "Does not create an executable. Just a .IL file for eub to run." },
    { DOES_NOT_DISPLAY_BINDING_INFORMATION         , "Does not display binding information" },
    { DO_NOT_BUILD_THE_PROJECT_NOR_WRITE_A_BUILD_FILE, "Do not build the project nor write a build file" },
    { DO_NOT_DISPLAY_STATUS_MESSAGES               , "Do not display status messages" },
    { DUPLICATE_CASE_VALUE_USED                    , "duplicate case value used." },
    { DUPLICATE_ENTRY_CLAUSE_IN_A_LOOP_HEADER      , "duplicate entry clause in a loop header" },
    { DUPLICATE_LABEL_NAME                         , "Duplicate label name" },
    { DUPLICATE_MULTI_ASSIGN                       , "duplicate variables in left hand side of multiple assignment" },
    { ENABLE_ALL_WARNINGS                          , "Enable all warnings" },
    { ENABLE_DEBUG_MODE_FOR_GENERATED_CODE         , "Enable debug mode for generated code" },
    { END_OF_FILE_REACHED_WHILE_SEARCHING_FOR_END_IFDEF_TO_MATCH_IFDEF_ON_LINE_1, "End of file reached while searching for 'end ifdef' to match 'ifdef' on line [1]" },
    { END_OF_LINE_REACHED_WITH_NO_CLOSING          , `end of line reached with no closing "` },
    { ENTRY_IS_NOT_SUPPORTED_IN_FOR_LOOPS          , "entry is not supported in for loops" },
    { ENTRY_KEYWORD_IS_NOT_SUPPORTED_INSIDE_AN_IF_OR_SWITCH_BLOCK_HEADER, "entry keyword is not supported inside an if or switch block header" },
    { ENTRY_MUST_BE_INSIDE_A_LOOP                  , "entry must be inside a loop" },
    { ENTRY_STATEMENT_IS_BEING_USED_WITHOUT_A_CORRESPONDING_ENTRY_CLAUSE_IN_THE_LOOP_HEADER, "entry statement is being used without a corresponding entry clause in the loop header" },
    { ENUM_CONSTANTS_MUST_BE_ASSIGNED_AN_INTEGER   , "enum constants must be assigned an integer" },
    { ENUM_CONSTANTS_MUST_BE_INTEGERS              , "enum constants must be integers" },
    { ERASE_AN_EXISTING_COVERAGE_DATABASE_AND_START_A_NEW_COVERAGE_ANALYSIS, "Erase an existing coverage database and start a new coverage analysis." },
    { ERRORS_RESOLVING_THE_FOLLOWING_REFERENCES1   , "Errors resolving the following references:\n[1]" },
    { ERROR_CREATING_REGEX_FOR_COVERAGE_EXCLUSION_PATTERN_1, "Error creating regex for coverage exclusion pattern '[1]'" },
    { ERROR_IN_PARSING_SCIENTIFIC_NOTATION         , "Error in parsing scientific notation" },
    { ERROR_MUST_SPECIFY_THE_FILE_TO_BE_INTERPRETED_ON_THE_COMMAND_LINE, "\nERROR: Must specify the file to be interpreted on the command line\n" },
    { ERROR_MUST_SPECIFY_THE_FILE_TO_BE_TRANSLATED_ON_THE_COMMAND_LINE, "\nERROR: Must specify the file to be translated on the command line\n" },
    { ERROR_RESOLVING_FORWARD_REFERENCE_IN_CASE_FOR_1, "Error resolving forward reference in case for '[1]'" },
    { ERROR_WITH_TOKEN_PLAYBACK                    , "error with token playback" },
    { EUCEXE_OPTIONS_FILEEX_COMMON_OPTIONS         , "euc.exe [options] file.ex...\n common options:" },
    { EUCONSOLE                                    , "EuConsole" },
    { EUPHORIA_BINDER                              , "Euphoria Binder" },
    { EUPHORIA_INTERPRETER                         , "Euphoria Interpreter" },
    { EUPHORIA_TO_C_TRANSLATOR                     , "Euphoria to C Translator" },
    { EXCLUDE_FROM_COVERAGE                        , "Exclude from coverage" },
    { EXITBREAK_ARGUMENT_OUT_OF_RANGE              , "exit/break argument out of range" },
    { EXIT_MUST_BE_INSIDE_A_LOOP                   , "exit must be inside a loop" },
    { EXIT_STATEMENT_MUST_BE_INSIDE_A_LOOP         , "exit statement must be inside a loop" },
    { EXPECTED_1_NOT_2                             , "expected [1], not [2]" },
    { EXPECTED_AN_ATOM_STRING_OR_A_CONSTANT_ASSIGNED_AN_ATOM_OR_A_STRING, "expected an atom, string or a constant assigned an atom or a string" },
    { EXPECTED_END_OF_1_BLOCK_NOT_2                , "Expected end of [1] block, not [2]" },
    { EXPECTED_THEN_OR__NOT_1                      , "expected 'then' or ',', not [1]" },
    { EXPECTED_TO_SEE_AN_ASSIGNMENT_AFTER_1_SUCH_AS__OR, "expected to see an assignment after '[1]', such as =, +=, -=, *=, /= or &=" },
    { EXPECTED_TO_SEE_A_PARAMETER_DECLARATION_NOT  , "expected to see a parameter declaration, not ')'" },
    { EXPECTED__OR                                 , "expected ',' or ')'" },
    { EXPECTING_AS_OR_ENDOF_LINE_UNEXPECTED_TEXT_ON_INCLUDE_DIRECTIVE, "expecting 'as' or end-of line. Unexpected text on 'include' directive" },
    { EXPECTING_A_WORD_TO_FOLLOW_ELSIFDEF          , "Expecting a 'word' to follow 'elsifdef'" },
    { EXPECTING_END_IFDEF_TO_MATCH_IFDEF_ON_LINE_1 , "Expecting 'end ifdef' to match 'ifdef' on line [1]" },
    { EXPECTING_EXACTLY_EIGHT_HEXADECIMAL_DIGITS_TO_FOLLOW_THE_U, "Expecting exactly eight hexadecimal digits to follow the '\\U'" },
    { EXPECTING_EXACTLY_FOUR_HEXADECIMAL_DIGITS_TO_FOLLOW_THE_U, "Expecting exactly four hexadecimal digits to follow the '\\u'" },
    { EXPECTING_EXACTLY_TWO_HEXADECIMAL_DIGITS_TO_FOLLOW_THE_X, "Expecting exactly two hexadecimal digits to follow the '\\x'" },
    { EXPECTING_ONLY_0_1_OR_SPACE_TO_FOLLOW_THE_B  , "Expecting only '0', '1' or space to follow the '\\b'" },
    { EXPECTING_POSSIBLY_THEN_NOT_END_OF_LINE      , "expecting possibly 'then' not end of line" },
    { EXPECTING_THEN_ON_ELSIFDEF_LINE              , "Expecting 'then' on 'elsifdef' line" },
    { EXPECTING_TO_FIND_A_WORD_TO_DEFINE_BUT_REACHED_END_OF_LINE_FIRST, "Expecting to find a word to define but reached end of line first." },
    { EXPONENT_NOT_FORMED_CORRECTLY                , "exponent not formed correctly" },
    { EXTERNAL_DEBUGGER                            , "External debugger" },
    { FAILED_DUE_TO_INTERNAL_ERROR                 , "Failed due to internal error." },
    { FILE_1_USES_PUBLIC_SYMBOLS_FROM_2_BUT_DOES_NOT_INCLUDE_THAT_FILE, "File '[1]' uses public symbols from '[2]', but does not include that file." },
    { FILE_NAME_IS_MISSING                         , "file name is missing" },
    { FLAGS_TO_PASS_TO_COMPILER_OVERRIDES_INTERNAL_COMPILER_FLAGS, "Flags to pass to compiler (overrides internal compiler flags)" },
    { FLAGS_TO_PASS_TO_LINKER_OVERRIDES_INTERNAL_LINKER_FLAGS, "Flags to pass to linker (overrides internal linker flags)" },
    { FORCE_BUILDING_EVEN_IF_FILE_IS_UPTODATE      , "Force building, even if file is up-to-date" },
    { FORCE_PREPROCESSING_REGARDLESS_OF_CACHE_STATE, "Force pre-processing regardless of cache state" },
    { FORWARD_REFERENCES_ARE_NOT_SUPPORTED_FOR_ENUMS, "Forward references are not supported for enums" },
    { FOUND_1_2_BUT_WAS_EXPECTING_A_PARAMETER_NAME_INSTEAD, "found [1] '[2]' but was expecting a parameter name instead." },
    { FOUND_1_BUT_EXPECTED_ELSE_AN_ATOM_STRING_CONSTANT_OR_ENUM, "found [1] but expected 'else', an atom, string, constant or enum" },
    { FOUND_1_BUT_WAS_EXPECTING_A_PARAMETER_NAME_INSTEAD, "found [1] but was expecting a parameter name instead." },
    { FOUND__1__BUT_WAS_EXPECTING_AN_IDENTIFIER_NAME, "found ... [1] ... but was expecting an identifier name" },
    { FRACTIONAL_PART_OF_NUMBER_IS_MISSING         , "fractional part of number is missing" },
    { GENERATECOMPILE_ALL_FILES_IN_DIR             , "Generate/compile all files in 'dir'" },
    { GENERATE_A_FULL_MAKEFILE                     , "Generate a full Makefile" },
    { GENERATE_A_PARTIAL_PROJECT_MAKEFILE          , "Generate a partial project Makefile" },
    { GOTO_STATEMENT_WITHOUT_A_STRING_LABEL        , "Goto statement without a string label." },
    { HEX_NUMBER_NOT_FORMED_CORRECTLY              , "hex number not formed correctly" },
    { ILLEGAL_CHARACTER                            , "illegal character" },
    { ILLEGAL_CHARACTER_ASCII_0_AT_LINECOL_12      , "illegal character (ASCII 0) at line:col [1]:[2]" },
    { ILLEGAL_CHARACTER_IN_SOURCE                  , "illegal character in source" },
    { IL_CODE_IS_NOT_IN_PROPER_FORMAT              , "IL code is not in proper format" },
    { INCLUDES_ARE_NESTED_TOO_DEEPLY               , "includes are nested too deeply" },
    { INCLUDES_SYMBOL_NAMES_IN_IL_DATA             , "Includes symbol names in IL data" },
    { INDICATE_FILES_OR_DIRECTORIES_FOR_WHICH_TO_GATHER_COVERAGE_STATISTICS, "Indicate files or directories for which to gather coverage statistics" },
    { INTEGER_OR_CONSTANT_EXPECTED                 , "integer or constant expected" },
    { INTERNAL_DEREF_PROBLEM                       , "internal: deref problem" },
    { INTERNAL_ERRORT1                             , "Internal Error:\n\t[1]\n" },
    { INTERNAL_ERROR_AT_12T3                       , "Internal Error at [1]:[2]\n\t[3]\n" },
    { INTERNAL_ERROR_BINDING_SEEK_TO_CHECKSUM_AREA_FAILED, "Internal error; Binding seek to checksum area failed!" },
    { INTERNAL_ERROR_BINDING_SEEK_TO_START_OF_IL_FAILED, "Internal error; Binding seek to start of IL failed!" },
    { INTERNAL_ERROR_BOUND_FILE_MAY_HAVE_BEEN_CORRUPTED, "Internal error; Bound file may have been corrupted." },
    { INTERNAL_ERROR_SEEK_TO_IL_START_FAILED       , "Internal error; seek to IL start failed!" },
    { INTERNAL_NESTED_CALL_PARSING_ERROR           , "internal nested call parsing error" },
    { INVALID_CHARACTER_IN_HEX_STRING              , "Invalid character in HEX string" },
    { INVALID_MAXIMUM_FILE_SIZE                    , "Invalid maximum file size" },
    { INVALID_NUMBER_BASE_SPECIFIER_1              , "Invalid number base specifier '[1]'" },
    { INVALID_OPTION_1                             , "Invalid option: [1]" },
    { KEEP_THE_GENERATED_FILES                     , "Keep the generated files" },
    { LEAVING_TOO_MANY_BLOCKS_1__2                 , "leaving too many blocks [1] > [2]" },
    { LINKING_100_1                                , "Linking 100% [1]" },
    { LINK_RESOURCE_FILE_INTO_RESULTING_EXECUTABLE , "Link resource file into resulting executable" },
    { LIST_UNUSED_DELETED_SYMBOLS_IN_DELETEDTXT    , "List unused (deleted) symbols in 'deleted.txt'" },
    { MAY_NOT_ASSIGN_TO_A_FORLOOP_VARIABLE         , "may not assign to a for-loop variable" },
    { MAY_NOT_CHANGE_THE_VALUE_OF_A_CONSTANT       , "may not change the value of a constant" },
    { MISMATCHED_ELSE_SHOULD_THIS_BE_AN_ELSEDEF_TO_MATCH_IFDEF_ON_LINE_1, "Mismatched 'else'. Should this be an 'elsedef' to match 'ifdef' on line [1]" },
    { MISMATCHED_END_IF_SHOULD_THIS_BE_AN_END_IFDEF_TO_MATCH_IFDEF_ON_LINE_1, "Mismatched 'end if'. Should this be an 'end ifdef' to match 'ifdef' on line [1]" },
    { MISSING_CLOSING_QUOTE_ON_FILE_NAME           , "missing closing quote on file name" },
    { MISSING_CMD_PARAMETER                        , "Command line argument [1] requires a parameter" },
    { MISSING_DEFAULT_NAMESPACE_QUALIFIER          , "missing default namespace qualifier" },
    { MISSING_NAMESPACE_QUALIFIER                  , "missing namespace qualifier" },
    { MSG_1                                        , "[1] " },
    { MSG_12__BUILTIN_ROUTINE_3_OVERRIDDEN         , "[1]:[2] - built-in routine [3]() overridden" },
    { MSG_12__BUILTIN_ROUTINE_3_OVERRIDDEN_AGAIN   , "[1]:[2] - built-in routine [3]() overridden again" },
    { MSG_12__CALL_TO_3_MIGHT_BE_SHORTCIRCUITED    , "[1]:[2] - call to [3]() might be short-circuited" },
    { MSG_12__EMPTY_CASE_BLOCK_WITHOUT_FALLTHRU    , "[1]:[2] - empty case block without fallthru" },
    { MSG_12__IDENTIFIER_3_IN_4_IS_NOT_INCLUDED    , "[1]:[2] - identifier '[3]' in '[4]' is not included" },
    { MSG_12__NO_CASE_ELSE_SUPPLIED                , "[1]:[2] - no 'case else' supplied." },
    { MSG_12__STATEMENT_AFTER_3_WILL_NEVER_BE_EXECUTED, "[1]:[2] - statement after [3] will never be executed" },
    { MSG_12__UNKNOWN_WARNING_NAME_3               , "[1]:[2] - Unknown warning name [3]" },
    { MSG_1C_FILES_WERE_CREATED                    , "\n[1].c files were created." },
    { MSG_1_AND_FOLLOWS_2                          , "[1] 'and' follows '[2]'" },
    { MSG_1_CONFLICTS_WITH_A_FILE_NAME_USED_INTERNALLY_BY_THE_TRANSLATOR, "[1] conflicts with a file name used internally by the Translator" },
    { MSG_1_DUPLICATE_NOT                          , "[1] duplicate 'not'" },
    { MSG_1_HAS_NOT_BEEN_DECLARED                  , "'[1]' has not been declared" },
    { MSG_1_IS_DEPRECATED                          , "[1] is deprecated" },
    { MSG_1_IS_MISSING_DEFINED_WORD_BEFORE_AND     , "[1] is missing defined word before 'and'" },
    { MSG_1_IS_MISSING_DEFINED_WORD_BEFORE_OR      , "[1] is missing defined word before 'or'" },
    { MSG_1_IS_MISSING_DEFINED_WORD_BEFORE_THEN    , "[1] is missing defined word before 'then'" },
    { MSG_1_IS_NOT_SUPPORTED_IN_EUPHORIA_FOR_2     , "[1] is not supported in Euphoria for [2]" },
    { MSG_1_IS_NOT_SUPPORTED_IN_THIS_PLATFORM      , "'[1]' is not supported in this platform" },
    { MSG_1_NEEDS_2_ARGUMENT                       , "'[1]' needs [2] argument" },
    { MSG_1_NEEDS_2_ARGUMENTS                      , "'[1]' needs [2] arguments" },
    { MSG_1_NEEDS_AT_LEAST_2_PARAMETERS_BUT_SOME_NONDEFAULTABLE_ARGUMENTS_ARE_MISSING, "[1]() needs at least [2] parameters, but some non-defaultable arguments are missing." },
    { MSG_1_NOT_UNDERSTOOD                         , "[1] not understood" },
    { MSG_1_ONLY_NEEDS_2_ARGUMENT                  , "'[1]' only needs [2] argument" },
    { MSG_1_ONLY_NEEDS_2_ARGUMENTS                 , "'[1]' only needs [2] arguments" },
    { MSG_1_OR_FOLLOWS_2                           , "[1] 'or' follows '[2]'" },
    { MSG_1_THEN_FOLLOWS_2                         , "[1] 'then' follows '[2]'" },
    { MSG_1_THEN_FOLLOWS_NOT                       , "[1] 'then' follows 'not'" },
    { MSG_1_WORD_MUST_BE_AN_IDENTIFIER             , "[1] word must be an identifier" },
    { MSG_1__MODULE_CONSTANT_2_IS_NOT_USED         , "[1] - module constant '[2]' is not used" },
    { MSG_1__MODULE_VARIABLE_2_IS_ASSIGNED_BUT_NEVER_USED, "[1] - module variable '[2]' is assigned but never used" },
    { MSG_1__MODULE_VARIABLE_2_IS_NEVER_ASSIGNED_A_VALUE, "[1] - module variable '[2]' is never assigned a value" },
    { MSG_1__MODULE_VARIABLE_2_IS_NOT_USED         , "[1] - module variable '[2]' is not used" },
    { MSG_1__PARAMETER_2_OF_3_IS_ASSIGNED_BUT_NEVER_USED, "[1] - parameter '[2]' of [3]() is assigned but never used" },
    { MSG_1__PARAMETER_2_OF_3_IS_NOT_USED          , "[1] - parameter '[2]' of [3]() is not used" },
    { MSG_1__PRIVATE_VARIABLE_2_OF_3_IS_ASSIGNED_BUT_NEVER_USED, "[1] - private variable '[2]' of [3]() is assigned but never used" },
    { MSG_1__PRIVATE_VARIABLE_2_OF_3_IS_NEVER_ASSIGNED_A_VALUE, "[1] - private variable '[2]' of [3] is never assigned a value" },
    { MSG_1__PRIVATE_VARIABLE_2_OF_3_IS_NOT_USED   , "[1] - private variable '[2]' of [3]() is not used" },
    { MSG_CC_PREFIX                                , "Prefix for compiler and related binaries" },
    { MSG_DELETED                                  , "-deleted-" },
    { MSG_DELETED_A                                , "-deleted-" },
    { MSG_DELETED_B                                , "-deleted-" },
    { MSG_DELETED_C                                , "-deleted-" },
    { MSG_ENDOFFILE                                , "<end-of-file>\n" },
    { MSG_END_HAS_NO_MATCHING_1                    , "'end' has no matching '[1]'" },
    { MSG_GLOBAL_MUST_BE_FOLLOWED_BYA_TYPE_CONSTANT_ENUM_PROCEDURE_TYPE_OR_FUNCTION, "'global' must be followed by:\n<a type>, 'constant', 'enum', 'procedure', 'type' or 'function'" },
    { MSG_PRESS_ANY_KEY_AND_WINDOW_WILL_CLOSE      , "\n(press any key and window will close ...)" },
    { MSG_PUBLIC_OR_EXPORT_MUST_BE_FOLLOWED_BYA_TYPE_CONSTANT_ENUM_PROCEDURE_TYPE_OR_FUNCTION, "'public' or 'export' must be followed by:\n<a type>, 'constant', 'enum', 'procedure', 'type' or 'function'" },
    { MSG_TAB_CHARACTER_FOUND_IN_STRING__USE_T_INSTEAD, """tab character found in string - use \t instead""" },
    { MSG_WITHOUT_FALLTHRU_IS_ONLY_VALID_IN_A_SWITCH_STATEMENT, "'without fallthru' is only valid in a switch statement" },
    { MSG_WITH_ENTRY_IS_ONLY_VALID_ON_A_WHILE_OR_LOOP_STATEMENT, "'with entry' is only valid on a while or loop statement" },
    { MSG_WITH_FALLTHRU_IS_ONLY_VALID_IN_A_SWITCH_STATEMENT, "'with fallthru' is only valid in a switch statement" },
    { MSG__GENERATING                              , " generating" },
    { MSG__MAY_ONLY_BE_ON_THE_FIRST_LINE_OF_A_PROGRAM, "#! may only be on the first line of a program" },
    { MSG__MUST_ONLY_APPEAR_BETWEEN__AND__OR_AS_THE_LAST_ITEM_IN_A_SEQUENCE_LITERAL, "'$' must only appear between '[[]' and ']' or as the last item in a sequence literal." },
    { MSG__TRANSLATOR_OPTIONS                      , "\n translator options:" },
    { MULTITASKING_OPERATIONS_ARE_NOT_SUPPORTED_IN_A_DLL_OR_SO, "Multitasking operations are not supported in a .dll or .so" },
    { NEGATIVE_REF_COUNT_FOR_1                     , "negative ref count for [1]" },
    { NONSTANDARD_LIBRARY                          , "Use a non-standard library when building a shared object" },
    { NOT_AN_IL_FILE                               , "not an IL file!" },
    { NOT_EXPECTING_ANYTHING_ON_SAME_LINE_AS_ELSDEF, "Not expecting anything on same line as 'elsdef'" },
    { NOT_EXPECTING_ELSE                           , "Not expecting 'else'" },
    { NOT_EXPECTING_ELSIF                          , "Not expecting 'elsif'" },
    { NOT_EXPECTING_TO_SEE_1_HERE                  , "Not expecting to see '[1]' here" },
    { NO_EUPHORIA_IL_CODE_TO_EXECUTE               , "no Euphoria IL code to execute" },
    { NO_FILE_TO_BIND_WAS_SUPPLIED                 , "No file to bind was supplied." },
    { NO_ROUTINE_ID_FOR_1                          , "no routine id for [1]" },
    { NO_VALUE_RETURNED_FROM_FUNCTION              , "no value returned from function" },
    { NO_WORD_WAS_FOUND_FOLLOWING_1                , "no 'word' was found following [1]" },
	{ NUMBER_IS_TOO_SMALL                          , "The number specified here is too small."},
	{ NUMBER_IS_TOO_BIG                            , "The number specified here is too big."},
    { NUMBER_NOT_FORMED_CORRECTLY                  , "number not formed correctly" },
    { OBSOLETE_IL_FILE_PLEASE_RECREATE_IT_USING_EUPHORIA_40_OR_LATER, "Obsolete .il file. Please recreate it using Euphoria 4.0 or later." },
    { ONLY_ENUMS_MAY_BE_DECLARED_AS_TYPES          , "Only enums may be declared as types" },
    { ONLY_INTEGER_LITERALS_CAN_USE_THE_01_FORMAT  , "Only integer literals can use the '0[1]' format" },
    { ONLY_ONE_DECIMAL_POINT_ALLOWED               , "only one decimal point allowed" },
    { OR_TYPE_T1_IS_1_T2_IS_2                      , "or_type: t1 is [1], t2 is [2]\n" },
    { OUT_OF_MEMORY__TURN_OFF_TRACE_AND_PROFILE    , "out of memory - turn off trace and profile" },
    { OVERRIDES_THE_VALUE_OF_EUDIR                 , "Overrides the value of EUDIR" },
    { PATH_TO_BACKEND_RUNNER_TO_USE_FOR_BINDING_IGNORED_WHEN_SHROUDING, "Path to backend runner to use for binding (ignored when shrouding)" },
    { PAUSED_PRESS_ANY_KEY                         , "\nPaused: press any key ..." },
    { PREPARES_A_FILE_FOR_USE_ON_WINDOWS           , "Prepares a file for use on Windows" },
    { PRESS_ENTER                                  , "\nPress Enter\n" },
    { PRESS_ENTER_TO_CONTINUE_Q_TO_QUIT            , "\nPress Enter to continue, q to quit\n" },
    { PROGRAM_INCLUDES_TOO_MANY_FILES              , "program includes too many files" },
    { PUNCTUATION_MISSING_IN_BETWEEN_NUMBER_AND_1  , "Punctuation missing in between number and '[1]'" },
    { RAW_STRING_LITERAL_FROM_LINE_1_NOT_TERMINATED, "Raw string literal from line [1] not terminated." },
    { RESOURCE_FILE_DOES_NOT_EXIST__1              , "Resource file does not exist:\n    [1]" },
    { RETRY_MUST_BE_INSIDE_A_LOOP                  , "retry must be inside a loop" },
    { RETRY_STATEMENT_MUST_BE_INSIDE_A_LOOP        , "retry statement must be inside a loop" },
    { RETURN_MUST_BE_INSIDE_A_PROCEDURE_OR_FUNCTION, "return must be inside a procedure or function" },
    { SAMPLE_SIZE_MUST_BE_A_POSITIVE_INTEGER       , "sample size must be a positive integer" },
    { SCANNER_UNHANDLED_CLASS_1                    , "Scanner unhandled class [1]" },
    { SETUP_A_PREPROCESSOR                         , "Setup a pre-processor" },
    { SET_PRIVATE_SCOPE__UNHANDLED_SCOPE_1         , "Set Private Scope - unhandled scope [1]" },
    { SET_THE_COMPILER_DIRECTORY                   , "Set the compiler directory" },
    { SET_THE_COMPILER_TO_DJGPP                    , "Set the compiler to DJGPP" },
    { SET_THE_COMPILER_TO_GCC                      , "Set the compiler to GCC" },
    { SET_THE_COMPILER_TO_WATCOM                   , "Set the compiler to Watcom" },
    { SET_THE_NUMBER_OF_C_STATEMENTS_PER_GENERATED_FILE_BEFORE_SPLITTING, "Set the number of C statements per generated file before splitting." },
    { SET_THE_OUTPUT_FILENAME                      , "Set the output filename" },
    { SET_THE_PLATFORM_FOR_THE_TRANSLATED_CODE     , "Set the platform for the translated code" },
    { SET_THE_STACK_SIZE_WATCOM                    , "Set the stack size (Watcom)" },
    { SHOULD_THIS_BE_ELSEDEF_FOR_THE_IFDEF_ON_LINE_1, "Should this be 'elsedef' for the ifdef on line [1]?" },
    { SHOULD_THIS_BE_ELSIFDEF_FOR_THE_IFDEF_ON_LINE_1, "Should this be 'elsifdef' for the ifdef on line [1]?" },
    { SINGLEQUOTE_CHARACTER_IS_EMPTY               , "single-quote character is empty" },
    { SKIPPING__130_2_UPTODATE                     , "Skipping  [1:3.0]% [2] (up-to-date)" },
    { SORRY_TOO_MANY_C_FILES_WITH_THE_SAME_BASE_NAME, "Sorry, too many .c files with the same base name" },
    { SPECIFY_ADDITIONAL_COMPILER_FLAGS_TO_TRANSLATOR, "Specify additional compiler flags to translator!" },
    { SPECIFY_ADDITIONAL_LINKER_FLAGS_FOR_TRANSLATOR, "Specify additional linker flags for translator!" },
    { SPECIFY_A_CONFIGURATION_FILE                 , "Specify a configuration file" },
    { SPECIFY_THE_FILENAME_FOR_THE_COVERAGE_DATABASE, "Specify the filename for the coverage database." },
    { SPECIFY_THE_TARGET_ARCHITECTURE_X86_X86_64_ARM, "Specify the target architecture (X86, X86_64, ARM)" },
    { STATEMENTS_HAVE_BEEN_INSERTED_TO_TRACE_EXECUTION_OF_YOUR_PROGRAM, "Statements have been inserted to trace execution of your program." },
    { STATUS_1_COMMAND_2                           , "Status: [1] Command: [2]" },
    { STATUS_1_COMMAND_2_A                         , "Status: [1] Command: [2]" },
    { SYNTAX_ERROR__EXPECTED_TO_SEE_1_AFTER_2_NOT_3, "Syntax error - expected to see [1] after [2], not [3]" },
    { SYNTAX_ERROR__EXPECTED_TO_SEE_AN_EXPRESSION_NOT_1, "Syntax error - expected to see an expression, not [1]" },
    { SYNTAX_ERROR__EXPECTED_TO_SEE_POSSIBLY_1_NOT_2, "Syntax error - expected to see possibly [1], not [2]" },
    { SYNTAX_ERROR__UNKNOWN_NAMESPACE_1_USED       , "Syntax error - Unknown namespace '[1]' used" },
    { TEST_SYNTAX_ONLY_DO_NOT_EXECUTE              , "Test syntax only, do not execute" },
    { THERE_IS_NO_WATCOM_INSTALATION_UNDER_SPECIFIED_WATOM_PATH_1, "There is no watcom instalation under specified Watom Path [1]" },
    { THE_BUILTIN_1_IN_2_OVERRIDES_THE_GLOBALPUBLIC_1_IN3, "The built-in [1]() in [2] overrides the global/public [1]() in:[3]" },
    { THE_ENTRY_STATEMENT_CAN_NOT_BE_USED_IN_A_FOR_BLOCK, "the entry statement can not be used in a 'for' block" },
    { THE_ENTRY_STATEMENT_MUST_APPEAR_AT_MOST_ONCE_INSIDE_A_LOOP, "the entry statement must appear at most once inside a loop" },
    { THE_ENTRY_STATEMENT_MUST_APPEAR_INSIDE_A_LOOP, "the entry statement must appear inside a loop" },
    { THE_INNERMOST_BLOCK_CONTAINING_AN_ENTRY_STATEMENT_MUST_BE_THE_LOOP_IT_DEFINES_AN_ENTRY_IN, "the innermost block containing an entry statement must be the loop it defines an entry in." },
    { THE_LIST_OF_DELETED_SYMBOLS_IS_IN_DELETEDTXT , "The list of deleted symbols is in 'deleted.txt'" },
    { THE_NAME_OF_THE_EXECUTABLE_TO_CREATE_THE_DEFAULT_IS_THE_SAME_BASENAME_OF_THE_INPUT_FILE, "The name of the executable to create. The default is the same basename of the input file." },
    { THIS_OPCODE_1_SHOULD_NEVER_BE_EMITTED__SUBPROG_2, "This opcode ([1]) should never be emitted!  SubProg '[2]'" },
    { TOO_MANY_WARNING_ERRORS                      , "too many warning errors" },
    { TO_BUILD_YOUR_PROJECT_CHANGE_DIRECTORY_TO_1_AND_TYPE_23MAK, "To build your project, change directory to [1] and type [2][3].mak" },
    { TO_BUILD_YOUR_PROJECT_INCLUDE_1MAK_INTO_A_LARGER_MAKEFILE_PROJECT, "To build your project, include [1].mak into a larger Makefile project" },
    { TO_BUILD_YOUR_PROJECT_TYPE_12MAK             , "To build your project, type [1][2].mak" },
    { TO_RUN_YOUR_PROJECT_TYPE_1                   , "\nTo run your project, type [1]" },
    { TRACE_LINES_CMD                              , "Specify the number of lines to use in ctrace.out" },
    { TRANSLATING_CODE_PASS                        , "Translating code, pass: " },
    { TURN_ON_BATCH_PROCESSING_DO_NOT_PRESS_ENTER_ON_ERROR, "Turn on batch processing (do not \"Press Enter\" on error)" },
    { TYPES_MUST_HAVE_EXACTLY_ONE_PARAMETER        , "types must have exactly one parameter" },
    { TYPE_CHECK_ERROR_WHEN_INLINING_LITERAL       , "Type Check Error when inlining literal" },
    { TYPE_CHECK_ERROR__ASSIGNING_A_SEQUENCE_TO_AN_ATOM, "Type check error:  assigning a sequence to an atom" },
    { TYPE_MUST_RETURN_TRUE__FALSE_VALUE           , "type must return true / false value" },
    { UNABLE_TO_COMPILE_RESOURCE_FILE_1            , "Unable to compile resource file: [1]" },
    { UNABLE_TO_CREATE_WARNING_FILE_1              , "\nUnable to create warning file [1]" },
    { UNABLE_TO_LINK_1                             , "Unable to link [1]" },
    { UNABLE_TO_LINK_RESOURCE_FILE_1_INTO_EXECUTABLE_2, "Unable to link resource file [1] into executable [2]" },
    { UNHANDLED_INLINE_TYPE_1                      , "Unhandled inline type: [1]" },
    { UNKNOWN_ARCHITECTURE_1__SUPPORTED_ARCHITECTURES_ARE_2, "Unknown architecture: [1].  Supported architectures are: [2]" },
    { UNKNOWN_BLOCK_LABEL                          , "Unknown block label" },
    { UNKNOWN_BUILD_FILE_TYPE                      , "Unknown build file type" },
    { UNKNOWN_COMPILER                             , "Unknown compiler" },
    { UNKNOWN_COMPILER_TYPE_1                      , "Unknown compiler type: [1]" },
    { UNKNOWN_ESCAPE_CHARACTER                     , "unknown escape character" },
    { UNKNOWN_LABEL_1                              , "Unknown label '[1]'" },
    { UNKNOWN_MESSAGE_CODE_1                       , "Unknown message code: [1]" },
    { UNKNOWN_NAMESPACE_1_IN_DEFAULT_ARGUMENT      , "Unknown namespace \"[1]\" in default argument" },
    { UNKNOWN_OPCODE_1                             , "unknown opcode: [1]" },
    { UNKNOWN_OP_FOUND_WHEN_SHIFTING_CODE_1        , "Unknown op found when shifting code: [1]" },
    { UNKNOWN_PLATFORM_1__SUPPORTED_PLATFORMS_ARE_2, "Unknown platform: [1].  Supported platforms are: [2]" },
    { UNKNOWN_WITHWITHOUT_OPTION_1                 , "unknown with/without option '[1]'" },
    { UNRECOGNIZED_FORWARD_REFERENCE_TYPE_1_2      , "unrecognized forward reference type: [1] ([2])" },
    { USER_SUPPLIED_ICON_FILE_USED_IGNORED_WHEN_SHROUDING, "User supplied icon file used. (ignored when shrouding)" },
    { USER_SUPPLIED_LIBRARY_DOES_NOT_EXIST__1      , "User supplied library does not exist:\n    [1]" },
    { USE_A_NONSTANDARD_LIBRARY                    , "Use a non-standard library" },
    { USE_THE_MNOCYGWIN_FLAG_WITH_MINGW            , "Use the -mno-cygwin flag with MinGW" },
    { USING_MANAGED_MEMORY                         , "Using Managed Memory" },
    { USING_SYSTEM_MEMORY                          , "Using System Memory" },
    { VARIABLE_1_HAS_NOT_BEEN_DECLARED             , "Variable [1] has not been declared" },
    { VERBOSE_OUTPUT                               , "Verbose output" },
    { WARNING_1T2                                  , "Warning [1]:\n\t[2]\n" },
    { WARNING_NAMES_MUST_BE_ENCLOSED_IN            , "warning names must be enclosed in '(' ')'" },
    { WATCOM_CANNOT_BUILD_TRANSLATED_FILES_WHEN_THERE_IS_A_SPACE_IN_ITS_PARENT_FOLDERS, "Watcom cannot build translated files when there is a space in its parent folders" },
    { WATCOM_ENVIRONMENT_VARIABLE_IS_NOT_SET       , "WATCOM environment variable is not set" },
    { WATCOM_NEEDS_TO_HAVE_AN_INCLUDE_VARIABLE_SET_TO_ITS_INCLUDED_DIRECTORIES, "Watcom needs to have an INCLUDE variable set to its included directories" },
    { WATCOM_SHOULD_HAVE_THE_H_AND_THE_HNT_INCLUDES_AT_THE_FRONT_OF_THE_INCLUDE_VARIABLE__WATCOM_IS_LOCATED_IN_1__THE_INCLUDE_ENVIRONMENT_VARIABLE_IS_2, "Watcom should have the H and the H\\NT includes at the front of the INCLUDE variable.  Watcom is located in [1].  The INCLUDE environment variable is [2]." },
    { WINDOWS_ONLY_USES_THE_CURRENT_CONSOLE_RATHER_THAN_CREATING_A_NEW_CONSOLE_IGNORED_WHEN_SHROUDING, "Windows Only: Uses the current console rather than creating a new console (ignored when shrouding)" },
    { WRITE_ALL_WARNINGS_TO_THE_GIVEN_FILE_INSTEAD_OF_STDOUT, "Write all warnings to the given file instead of STDOUT" },
    { WRONG_NUMBER_OF_ARGUMENTS_SUPPLIED_FOR_FORWARD_REFERENCET1_2_3_4__EXPECTED_5_BUT_FOUND_6, "Wrong number of arguments supplied for forward reference\n\t[1] ([2]): [3] [4].  Expected [5], but found [6]." },
    { YOUR_CUSTOM_ICON_FILE_IS_TOO_LARGE           , "Your custom icon file is too large." },
    { YOU_MAY_NOW_RUN_1                            , "You may now run [1]" },
    { YOU_MAY_NOW_USE_1_TO_RUN_2                   , "You may now use [1] to run [2]" },
    $
}
	

public function GetMsgText( message_index MsgNum, integer WithNum = 1, object Args = {})
	integer idx = 1
	object msgtext

	-- First check localization databases
	msgtext = get_text( MsgNum, LocalizeQual, LocalDB )

	-- If not found, scan through hard-coded messages
	if atom(msgtext) then
		for i = 1 to length(StdErrMsgs) do
			if StdErrMsgs[i][1] = MsgNum then
				idx = i
				exit
			end if
		end for
		msgtext = StdErrMsgs[idx][2]
		if idx = 1 then
			Args = MsgNum
		end if
	end if

	if atom(Args) or length(Args) != 0 then
		msgtext = format(msgtext, Args)
	end if

	if WithNum != 0 then
		return sprintf("<%04d>:: %s", {MsgNum, msgtext})
	else
		return msgtext
	end if
end function

public procedure ShowMsg(integer Cons, object Msg, object Args = {}, integer NL = 1)

	if atom(Msg) then
		Msg = GetMsgText(floor(Msg), 0)
	end if

	if atom(Args) or length(Args) != 0 then
		Msg = format(Msg, Args)
	end if

	puts(Cons, Msg)

	if NL then
		puts(Cons, '\n')
	end if

end procedure
