
name: Euphoria

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-euphoria:
    name: Build Euphoria
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plat: ['LINUX','WINDOWS']
        arch: ['x86','x86_64']
    defaults:
      run:
        working-directory: ./source
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v2
      - name: Install Compilers (Linux x86)
        id: install-compilers-linux-x86
        if: matrix.plat == 'LINUX' && matrix.arch == 'x86'
        run: |
          sudo apt-get -qy install {binutils,gcc}-i686-linux-gnu
          echo "cc-prefix=i686-linux-gnu-" >> $GITHUB_ENV
      - name: Install Compilers (Windows x86)
        id: install-compilers-windows-x86
        if: matrix.plat == 'WINDOWS' && matrix.arch == 'x86'
        run: |
          sudo apt-get -qy install {binutils,gcc}-mingw-w64-i686
          echo "cc-prefix=i686-w64-mingw32-" >> $GITHUB_ENV
      - name: Install Compilers (Windows x64)
        id: install-compilers-windows-x64
        if: matrix.plat == 'WINDOWS' && matrix.arch == 'x86_64'
        run: |
          sudo apt-get -qy install {binutils,gcc}-mingw-w64-x86-64
          echo "cc-prefix=x86_64-w64-mingw32-" >> $GITHUB_ENV
      - name: Install Euphoria
        id: install-euphoria
        run: |
          wget -q https://github.com/OpenEuphoria/euphoria/releases/download/4.1.0/euphoria-4.1.0-Linux-x64-57179171dbed.tar.gz -O- | sudo tar -C /usr/local -xz euphoria-4.1.0-Linux-x64/{bin,include}
          cd /usr/local/bin; sudo find /usr/local/euphoria-4.1.0-Linux-x64/bin -type f -executable -exec ln -s {} \;
      - name: Run Configure
        id: run-configure
        run: ./configure --arch='${{matrix.arch}}' --plat='${{matrix.plat}}' --cc-prefix='${{env.cc-prefix}}'
      - name: Build Euphoria
        id: build-euphoria
        run: |
          make all
          make htmldoc
          echo "euphoria-version=$(./build/echoversion)" >> $GITHUB_ENV
      - name: Get Short Hash
        id: get-short-hash
        uses: benjlevesque/short-sha@v1.2
      - name: Upload Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: euphoria-${{env.euphoria-version}}-${{matrix.plat}}-${{matrix.arch}}-${{env.SHA}}
          path: |
            ./source/build/
            !./source/build/**/*.o
