
name: Euphoria

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        arch: ['x86','x86-64']
        plat: ['LINUX']
        include:
        - arch: 'x86'
          plat: 'LINUX'
          cc-prefix: 'i686-linux-gnu'
    defaults:
      run:
        working-directory: ./source
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Compilers
        if: matrix.cc-prefix
        run: sudo apt-get -y install binutils-${{matrix.cc-prefix}} gcc-${{matrix.cc-prefix}}
      - name: Install Euphoria
        run: |
          wget -q https://github.com/OpenEuphoria/euphoria/releases/download/4.1.0/euphoria-4.1.0-Linux-x64-57179171dbed.tar.gz -O- | sudo tar -C /usr/local -xz euphoria-4.1.0-Linux-x64/{bin,include}
          cd /usr/local/bin; sudo find /usr/local/euphoria-4.1.0-Linux-x64/bin -type f -executable -exec ln -s {} \;
      - name: Run Configure
        run: ./configure --arch='${{matrix.arch}}' --plat='${{matrix.plat}}' --cc-prefix='${{matrix.cc-prefix}}'
      - name: Build Euphoria
        run: make all
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: euphoria-4.1.0-${{matrix.plat}}-${{matrix.arch}}-${{github.run_id}}
          path: ./source/build/
